In [3]:
import numpy as np

np.int64(4)

In [5]:
a = np.array([23, 78, 45, 12, 89, 34, 67, 90, 11, 56], np.int8)
a.argmin()


np.int64(8)

In [6]:
a.argmax()

np.int64(7)

In [11]:
b = np.array([5, 99, 32, 74, 18, 61, 47, 83, 26, 10], np.int8)
b.argmin()

np.int64(0)

In [9]:
b.argmax()

np.int64(1)

In [10]:
c = np.array([88, 14, 39, 72, 6, 55, 91, 27, 63, 40])
c.argmin()


np.int64(4)

In [12]:
c.argmax()

np.int64(6)

In [13]:
d = np.array([19, 81, 33, 52, 7, 95, 24, 68, 44, 13])
d.argmin()


np.int64(4)

In [14]:
d.argmax()


np.int64(5)

In [15]:
e = np.array([62, 17, 76, 38, 93, 1, 54, 69, 43, 80])
e.argmin()



np.int64(4)

In [16]:
e.argmax()


np.int64(4)

In [25]:
# 2d array

f = np.array([[
    [1, 7, 3, 0, 9],
   [4, 2, 8, 5, 6],
   [9, 1, 0, 3, 7],
   [6, 8, 2, 4, 5],
   [3, 0, 7, 9, 1]
              ]])
print(f)
f.shape


[[[1 7 3 0 9]
  [4 2 8 5 6]
  [9 1 0 3 7]
  [6 8 2 4 5]
  [3 0 7 9 1]]]


np.int64(4)

In [30]:
g = np.array([[
    [0, 4, 7, 2, 8],
  [9, 1, 5, 6, 3],
  [2, 8, 0, 4, 7],
  [6, 3, 9, 1, 5],
  [7, 5, 2, 8, 0]

    
]])
print(g)
g.shape

[[[0 4 7 2 8]
  [9 1 5 6 3]
  [2 8 0 4 7]
  [6 3 9 1 5]
  [7 5 2 8 0]]]


(1, 5, 5)

In [27]:
h = np.array([[[2, 5, 8, 1, 6],
  [7, 3, 0, 9, 4],
  [1, 6, 2, 8, 5],
  [9, 4, 7, 3, 0],
  [8, 0, 5, 2, 1]]])
print(h)
h.shape

[[[2 5 8 1 6]
  [7 3 0 9 4]
  [1 6 2 8 5]
  [9 4 7 3 0]
  [8 0 5 2 1]]]


(1, 5, 5)

In [28]:
i = np.array([[
    [9, 2, 4, 7, 1],
  [3, 8, 5, 0, 6],
  [7, 1, 9, 2, 4],
  [0, 6, 3, 8, 5],
  [5, 4, 1, 9, 2]
]])
print(i)
i.shape

[[[9 2 4 7 1]
  [3 8 5 0 6]
  [7 1 9 2 4]
  [0 6 3 8 5]
  [5 4 1 9 2]]]


(1, 5, 5)

In [29]:
j = np.array([[
    
  [6, 0, 3, 8, 2],
  [1, 9, 4, 7, 5],
  [8, 2, 6, 1, 3],
  [5, 7, 0, 4, 9],
  [2, 3, 8, 6, 1]

]])
print(j)
j.shape


[[[6 0 3 8 2]
  [1 9 4 7 5]
  [8 2 6 1 3]
  [5 7 0 4 9]
  [2 3 8 6 1]]]


(1, 5, 5)

In [31]:
k = np.array([[

    [5, 8, 2, 4, 7],
  [1, 3, 9, 0, 6],
  [7, 2, 5, 8, 4],
  [0, 6, 1, 3, 9],
  [4, 9, 7, 2, 5]


]])
print(k)
k.shape

[[[5 8 2 4 7]
  [1 3 9 0 6]
  [7 2 5 8 4]
  [0 6 1 3 9]
  [4 9 7 2 5]]]


(1, 5, 5)

In [32]:
l = np.array([[
    [7, 1, 6, 3, 0],
  [2, 9, 4, 8, 5],
  [0, 3, 7, 1, 6],
  [5, 8, 2, 9, 4],
  [6, 4, 0, 7, 1]

]])
print(l)
l.shape


[[[7 1 6 3 0]
  [2 9 4 8 5]
  [0 3 7 1 6]
  [5 8 2 9 4]
  [6 4 0 7 1]]]


(1, 5, 5)

In [34]:
m = np.array([[

    [8, 3, 5, 1, 9],
  [4, 7, 0, 6, 2],
  [9, 1, 8, 3, 5],
  [6, 2, 4, 7, 0],
  [5, 0, 9, 8, 3]
]])
print(m)
m.shape

[[[8 3 5 1 9]
  [4 7 0 6 2]
  [9 1 8 3 5]
  [6 2 4 7 0]
  [5 0 9 8 3]]]


(1, 5, 5)

In [36]:
n = np.array([[

    [2, 7, 0, 5, 8],
  [6, 1, 3, 9, 4],
  [8, 5, 2, 7, 0],
  [9, 4, 6, 1, 3],
  [0, 3, 8, 2, 7]

]])
print(n)
n.shape


[[[2 7 0 5 8]
  [6 1 3 9 4]
  [8 5 2 7 0]
  [9 4 6 1 3]
  [0 3 8 2 7]]]


(1, 5, 5)

In [37]:
o = np.array([[
    [1, 7, 3, 0, 9],
  [4, 2, 8, 5, 6],
  [9, 1, 0, 3, 7],
  [6, 8, 2, 4, 5],
  [3, 0, 7, 9, 1]

]])
print(o)
o.shape

[[[1 7 3 0 9]
  [4 2 8 5 6]
  [9 1 0 3 7]
  [6 8 2 4 5]
  [3 0 7 9 1]]]


(1, 5, 5)

In [43]:
# 3d array
p = np.array([ [[9, 1, 0, 3, 7],
  [6, 8, 2, 4, 5],
  [3, 0, 7, 9, 1]], [[4, 2, 8, 5, 6],
  [9, 1, 0, 3, 7],
  [6, 8, 2, 4, 5]], [ [9, 1, 0, 3, 7],
  [6, 8, 2, 4, 5],
  [3, 0, 7, 9, 1]
],[[6, 1, 3, 9, 4],
  [8, 5, 2, 7, 0],
  [9, 4, 6, 1, 3]] ])
print(p)
p.shape

[[[9 1 0 3 7]
  [6 8 2 4 5]
  [3 0 7 9 1]]

 [[4 2 8 5 6]
  [9 1 0 3 7]
  [6 8 2 4 5]]

 [[9 1 0 3 7]
  [6 8 2 4 5]
  [3 0 7 9 1]]

 [[6 1 3 9 4]
  [8 5 2 7 0]
  [9 4 6 1 3]]]


(4, 3, 5)

In [44]:
q = np.array([ [
  [0, 1, 2, 3],
  [1, 2, 3, 0],
  [2, 3, 0, 1],
  [3, 0, 1, 2]
], [
  [4, 5, 6, 7],
  [5, 6, 7, 4],
  [6, 7, 4, 5],
  [7, 4, 5, 6]
], [
  [0, 2, 4, 6],
  [2, 4, 6, 0],
  [4, 6, 0, 2],
  [6, 0, 2, 4]
],[
  [9, 8, 7, 6],
  [8, 7, 6, 9],
  [7, 6, 9, 8],
  [6, 9, 8, 7]
]])
print(p)
p.shape

[[[9 1 0 3 7]
  [6 8 2 4 5]
  [3 0 7 9 1]]

 [[4 2 8 5 6]
  [9 1 0 3 7]
  [6 8 2 4 5]]

 [[9 1 0 3 7]
  [6 8 2 4 5]
  [3 0 7 9 1]]

 [[6 1 3 9 4]
  [8 5 2 7 0]
  [9 4 6 1 3]]]


(4, 3, 5)

In [4]:
r = np.array([[
  [8, 0, 3, 5],
  [0, 3, 5, 8],
  [3, 5, 8, 0],
  [5, 8, 0, 3]
],[
  [2, 9, 4, 7],
  [9, 4, 7, 2],
  [4, 7, 2, 9],
  [7, 2, 9, 4]
],[
  [4, 1, 7, 3],
  [1, 7, 3, 4],
  [7, 3, 4, 1],
  [3, 4, 1, 7]
],[
  [3, 6, 9, 2],
  [6, 9, 2, 3],
  [9, 2, 3, 6],
  [2, 3, 6, 9]
]])
print(r)
r.shape

[[[8 0 3 5]
  [0 3 5 8]
  [3 5 8 0]
  [5 8 0 3]]

 [[2 9 4 7]
  [9 4 7 2]
  [4 7 2 9]
  [7 2 9 4]]

 [[4 1 7 3]
  [1 7 3 4]
  [7 3 4 1]
  [3 4 1 7]]

 [[3 6 9 2]
  [6 9 2 3]
  [9 2 3 6]
  [2 3 6 9]]]


(4, 4, 4)

In [5]:
s = np.array([[
  [3, 6, 9, 2],
  [6, 9, 2, 3],
  [9, 2, 3, 6],
  [2, 3, 6, 9]
],[
  [3, 6, 9, 2],
  [6, 9, 2, 3],
  [9, 2, 3, 6],
  [2, 3, 6, 9]
],[
  [3, 6, 9, 2],
  [6, 9, 2, 3],
  [9, 2, 3, 6],
  [2, 3, 6, 9]
],[
  [3, 6, 9, 2],
  [6, 9, 2, 3],
  [9, 2, 3, 6],
  [2, 3, 6, 9]
]])
print(s)
s.shape

[[[3 6 9 2]
  [6 9 2 3]
  [9 2 3 6]
  [2 3 6 9]]

 [[3 6 9 2]
  [6 9 2 3]
  [9 2 3 6]
  [2 3 6 9]]

 [[3 6 9 2]
  [6 9 2 3]
  [9 2 3 6]
  [2 3 6 9]]

 [[3 6 9 2]
  [6 9 2 3]
  [9 2 3 6]
  [2 3 6 9]]]


(4, 4, 4)

In [6]:
t = np.array([[
  [0, 5, 1, 6],
  [5, 1, 6, 0],
  [1, 6, 0, 5],
  [6, 0, 5, 1]
],[
  [3, 6, 9, 2],
  [6, 9, 2, 3],
  [9, 2, 3, 6],
  [2, 3, 6, 9]
],[
  [9, 8, 7, 6],
  [8, 7, 6, 9],
  [7, 6, 9, 8],
  [6, 9, 8, 7]
],[
  [0, 1, 2, 3],
  [1, 2, 3, 0],
  [2, 3, 0, 1],
  [3, 0, 1, 2]
]])
print(t)
t.shape

[[[0 5 1 6]
  [5 1 6 0]
  [1 6 0 5]
  [6 0 5 1]]

 [[3 6 9 2]
  [6 9 2 3]
  [9 2 3 6]
  [2 3 6 9]]

 [[9 8 7 6]
  [8 7 6 9]
  [7 6 9 8]
  [6 9 8 7]]

 [[0 1 2 3]
  [1 2 3 0]
  [2 3 0 1]
  [3 0 1 2]]]


(4, 4, 4)

In [7]:
u = np.array([[[0, 1, 2, 3],
  [1, 2, 3, 0],
  [2, 3, 0, 1],
  [3, 0, 1, 2]
], [
  [4, 5, 6, 7],
  [5, 6, 7, 4],
  [6, 7, 4, 5],
  [7, 4, 5, 6]
], [
  [0, 2, 4, 6],
  [2, 4, 6, 0],
  [4, 6, 0, 2],
  [6, 0, 2, 4]
],[
  [9, 8, 7, 6],
  [8, 7, 6, 9],
  [7, 6, 9, 8],
  [6, 9, 8, 7]]])
print(u)
u.shape

[[[0 1 2 3]
  [1 2 3 0]
  [2 3 0 1]
  [3 0 1 2]]

 [[4 5 6 7]
  [5 6 7 4]
  [6 7 4 5]
  [7 4 5 6]]

 [[0 2 4 6]
  [2 4 6 0]
  [4 6 0 2]
  [6 0 2 4]]

 [[9 8 7 6]
  [8 7 6 9]
  [7 6 9 8]
  [6 9 8 7]]]


(4, 4, 4)

In [12]:
v = np.array([[[4, 5, 6, 7],
  [5, 6, 7, 4],
  [6, 7, 4, 5],
  [7, 4, 5, 6]
], [
  [0, 2, 4, 6],
  [2, 4, 6, 0],
  [4, 6, 0, 2],
  [6, 0, 2, 4]
],[
  [9, 8, 7, 6],
  [8, 7, 6, 9],
  [7, 6, 9, 8]
]])
print(v)
v.shape

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [13]:
w = np.array([[
  [0, 5, 1, 6],
  [5, 1, 6, 0],
  [1, 6, 0, 5],
  [6, 0, 5, 1]
],[[4, 5, 6, 7],
  [5, 6, 7, 4],
  [6, 7, 4, 5],
  [7, 4, 5, 6]
], [
  [0, 2, 4, 6],
  [2, 4, 6, 0],
  [4, 6, 0, 2],
  [6, 0, 2, 4]
]])
print(w)
w.shape

[[[0 5 1 6]
  [5 1 6 0]
  [1 6 0 5]
  [6 0 5 1]]

 [[4 5 6 7]
  [5 6 7 4]
  [6 7 4 5]
  [7 4 5 6]]

 [[0 2 4 6]
  [2 4 6 0]
  [4 6 0 2]
  [6 0 2 4]]]


(3, 4, 4)

In [14]:
x = np.array([[[6, 0, 3, 8, 2],
  [1, 9, 4, 7, 5],
  [8, 2, 6, 1, 3],
  [5, 7, 0, 4, 9],
  [2, 3, 8, 6, 1]
],[[6, 0, 3, 8, 2],
  [1, 9, 4, 7, 5],
  [8, 2, 6, 1, 3],
  [5, 7, 0, 4, 9],
  [2, 3, 8, 6, 1]
  ],[[6, 0, 3, 8, 2],
  [1, 9, 4, 7, 5],
  [8, 2, 6, 1, 3],
  [5, 7, 0, 4, 9],
  [2, 3, 8, 6, 1]
    ]])
print(x)
x.shape

[[[6 0 3 8 2]
  [1 9 4 7 5]
  [8 2 6 1 3]
  [5 7 0 4 9]
  [2 3 8 6 1]]

 [[6 0 3 8 2]
  [1 9 4 7 5]
  [8 2 6 1 3]
  [5 7 0 4 9]
  [2 3 8 6 1]]

 [[6 0 3 8 2]
  [1 9 4 7 5]
  [8 2 6 1 3]
  [5 7 0 4 9]
  [2 3 8 6 1]]]


(3, 5, 5)

In [16]:
y = np.array([[[2, 5, 8, 1, 6],
  [7, 3, 0, 9, 4],
  [1, 6, 2, 8, 5],
  [9, 4, 7, 3, 0],
  [8, 0, 5, 2, 1]], [[2, 5, 8, 1, 6],
  [7, 3, 0, 9, 4],
  [1, 6, 2, 8, 5],
  [9, 4, 7, 3, 0],
  [8, 0, 5, 2, 1]],[[2, 5, 8, 1, 6],
  [7, 3, 0, 9, 4],
  [1, 6, 2, 8, 5],
  [9, 4, 7, 3, 0],
  [8, 0, 5, 2, 1]]])
print(y)
y.shape

[[[2 5 8 1 6]
  [7 3 0 9 4]
  [1 6 2 8 5]
  [9 4 7 3 0]
  [8 0 5 2 1]]

 [[2 5 8 1 6]
  [7 3 0 9 4]
  [1 6 2 8 5]
  [9 4 7 3 0]
  [8 0 5 2 1]]

 [[2 5 8 1 6]
  [7 3 0 9 4]
  [1 6 2 8 5]
  [9 4 7 3 0]
  [8 0 5 2 1]]]


(3, 5, 5)

In [ ]:
z = np.array([[
  [0, 1, 2],
  [1, 2, 0],
  [2, 0, 1]
],[
  [3, 4, 5],
  [4, 5, 3],
  [5, 3, 4]
],)
print(s)
z.shape