In [2]:
'''numpy is a python library
is is used to work with array
numpy is fundamental packadge for sceintific computing in python
numpy is a python library that provides a multidimensional array object'''
import numpy as np

In [2]:
#array:- array is collection of similar data type items stored in continious memory allocation

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
type(a)

numpy.ndarray

In [5]:
id(a[1])             #to get memory allocation

1459776352496

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])              #1d array
print(a)
print(type(a))
a.shape

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


(6,)

In [7]:
b = np.array([[1, 2, 3], [3, 4, 5]])                #2d array:- element stored in row and column
print(b)
print(type(a))
b.shape

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>


(2, 3)

In [8]:
c = np.array([[[1, 2], [3,4]],[[5,6], [7,8]]])
print(c)
print(type(c))
c.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


(2, 2, 2)

In [9]:
a = np.array([1, 2, 3, 4])
print(type(a))
a.shape

<class 'numpy.ndarray'>


(4,)

In [12]:
k = np.array([[1, 2, 3], [5, 6, 7], [4, 5, 6, ]])
print(k)
print(type(k))
k.shape

[[1 2 3]
 [5 6 7]
 [4 5 6]]
<class 'numpy.ndarray'>


(3, 3)

In [14]:
c = np.array([[[1, 2, 5], [3,4,5]],[[5,6,6], [7,8,7]], [[2,3,7],[4,5,7]]])
print(c)
print(type(c))
c.shape

[[[1 2 5]
  [3 4 5]]

 [[5 6 6]
  [7 8 7]]

 [[2 3 7]
  [4 5 7]]]
<class 'numpy.ndarray'>


(3, 2, 3)

In [15]:
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 5, 5])
print(d)

[1 2 3 4 5 6 7 8 9 1 3 5 5]


In [17]:
e = np.array([[1, 2, 3, 4, 5, 6, 7], [6, 7, 5, 4, 3, 2, 1],[9, 8, 6, 5, 7, 4, 3],[1, 0, 3, 6, 6, 7, 3],[3, 5, 0, 8, 9, 7, 1]])
print(e)
e.shape

[[1 2 3 4 5 6 7]
 [6 7 5 4 3 2 1]
 [9 8 6 5 7 4 3]
 [1 0 3 6 6 7 3]
 [3 5 0 8 9 7 1]]


(5, 7)

In [7]:
f = np.array([[[1, 2, 3, 4],[5, 6, 7,8],[9, 0, 3, 5]], [[9, 0, 6, 4], [8, 9, 0,5], [5, 6, 7, 8]], [[5, 7, 0, 1], [3, 4, 6, 0], [1, 3, 5, 8]], [[8, 9, 0, 4], [4, 6, 7, 8], [6, 7, 8, 9]]])
print(f)
f.shape

[[[1 2 3 4]
  [5 6 7 8]
  [9 0 3 5]]

 [[9 0 6 4]
  [8 9 0 5]
  [5 6 7 8]]

 [[5 7 0 1]
  [3 4 6 0]
  [1 3 5 8]]

 [[8 9 0 4]
  [4 6 7 8]
  [6 7 8 9]]]


(4, 3, 4)

In [11]:
xp =np.array([2, 3, 55, 7, 11], np.int8)
xp


array([ 2,  3, 55,  7, 11], dtype=int8)

In [12]:
xp.argmax()           # to find location of maximum value

np.int64(2)

In [13]:
xp.argmin()       # to find minimum value

np.int64(0)

In [3]:
bita = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [7]:
print(bita)
bita.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(4, 2, 3)

In [8]:
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
k = np.ones((10,10,2))                 #to perform the quick array need((ones))
print(k)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  

In [10]:
k.shape

(10, 10, 2)

In [13]:
b = np.zeros((10, 2, 4))
print(b)
b.shape

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


(10, 2, 4)

In [14]:
l =np.random.random((4, 5, 6))
print(l)
l.shape

[[[0.45542815 0.80714504 0.41852297 0.37465516 0.6896452  0.07876348]
  [0.24258177 0.96239046 0.33350719 0.19106627 0.01601633 0.20241717]
  [0.00364846 0.69892756 0.29483645 0.74163767 0.69407608 0.40450142]
  [0.3247777  0.76545953 0.98564702 0.30473001 0.11878312 0.42365239]
  [0.51395582 0.74117001 0.01121088 0.6678751  0.71373984 0.34572741]]

 [[0.21383745 0.07488122 0.74465833 0.94444787 0.78990085 0.65949413]
  [0.07466522 0.560066   0.71177023 0.60191807 0.65839466 0.83584748]
  [0.58785176 0.84439275 0.76908215 0.88121412 0.00634249 0.86790677]
  [0.9720813  0.79094469 0.7634606  0.90976157 0.94916362 0.02605953]
  [0.87269549 0.43744772 0.08585976 0.34447154 0.44530726 0.0549414 ]]

 [[0.74408703 0.67156138 0.99352168 0.72656658 0.38078689 0.96419892]
  [0.79833039 0.45899974 0.97320432 0.38887089 0.53378618 0.18214224]
  [0.85759702 0.95874903 0.49544045 0.59083842 0.42673541 0.03043891]
  [0.22102719 0.83363156 0.93575736 0.3143426  0.39756468 0.50299483]
  [0.83212314 0.

(4, 5, 6)

In [20]:
s = np.arange(20).reshape(2,5,2)
print(s)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [21]:
t = np.arange(50)                  #one dimensional array
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [22]:
t = np.arange(50).reshape(5,10)              #two dimensional array
print(t)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [23]:
t = np.arange(50).reshape(5,5,2)                 #three dimensional array-
print(t)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]]]


In [26]:
linspace_array = np.linspace(0,25,6)            #we count from first
print(linspace_array)

[ 0.  5. 10. 15. 20. 25.]


In [3]:
xp = np.array([[2,1,7,4],[3,2,8,2],[4,3,2,1],[8,5,8,3]])
print(xp)

[[2 1 7 4]
 [3 2 8 2]
 [4 3 2 1]
 [8 5 8 3]]


In [4]:
xp.sum(axis=0)

array([17, 11, 25, 10])

In [5]:
xp.sum(axis=1)

array([14, 15, 10, 24])

In [15]:
lm = [1, 2, 4, 6, 8, 10]
ty = np.array(lm)
print(type(ty))

<class 'numpy.ndarray'>


In [17]:
lm = [1, 2, 4, 6, 8, 10]
ty = np.array(lm)
print(lm)
print(type(ty))

[1, 2, 4, 6, 8, 10]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])

print("sum", np.sum(x))
print("mean", np.mean(x))
rint("median", np.mea(x))


In [3]:
w = np.array([1,2,3,4,5,6,7])          #agregate math methods

print(np.sum(w))
print(np.mean(w))
print(np.median(w))
print(np.std(w))
print(np.var(w))
print(np.min(w))
print(np.max(w))

28
4.0
4.0
2.0
4.0
1
7


In [5]:
x = np.array([5,6,7])

print("original array:", x)
print("sine:", np.sin(x))
print("cosine:", np.cos(x))
print("TANGENT:", np.tan(x))




original array: [5 6 7]
sine: [-0.95892427 -0.2794155   0.6569866 ]
cosine: [0.28366219 0.96017029 0.75390225]
TANGENT: [-3.38051501 -0.29100619  0.87144798]


In [6]:
#calculate(sine theta)
print("sine 30:", np.sin(np.radians(30)))

sine 30: 0.49999999999999994


In [7]:
#stacking Arrays         --- vertically
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#stacking Arrays         --- horizontally
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack((a, b))


array([1, 2, 3, 4, 5, 6])

In [11]:
np.column_stack((a, b))          #adding two different array as a column

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
x = np.array([23, 45, 67, 87, 90, 87, 65, 87, 90, 32, 54, 43, 65, 13, 23, 22, 67, 56, 32, 54, 65, 76, 43, 21, 12, 45])
y = np.array([27, 48, 68, 85, 90, 87, 65, 87, 90, 32, 54, 89, 65, 13, 23, 22, 89, 96, 82, 54, 65, 36, 73, 28, 6, 7])

np.column_stack((x, y))


array([[23, 27],
       [45, 48],
       [67, 68],
       [87, 85],
       [90, 90],
       [87, 87],
       [65, 65],
       [87, 87],
       [90, 90],
       [32, 32],
       [54, 54],
       [43, 89],
       [65, 65],
       [13, 13],
       [23, 23],
       [22, 22],
       [67, 89],
       [56, 96],
       [32, 82],
       [54, 54],
       [65, 65],
       [76, 36],
       [43, 73],
       [21, 28],
       [12,  6],
       [45,  7],
       [ 9,  5]])

In [20]:
# indexing slicing printing
print(x[25])             #indexing

45


In [22]:
print(x[1:5])               #slicing

[45 67 87 90]


In [25]:
print(x[x>50])               #filtering


[67 87 90 87 65 87 90 54 65 67 56 54 65 76]


In [29]:
#splitting the array             only of same sixed 
q = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 0])
np.split(q, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 0])]

In [31]:
r = np.array([[1, 2, 3, 4, 5, 6],
              [9, 8, 7, 6, 5, 4]])
np.hsplit(r, 2)

[array([[1, 2, 3],
        [9, 8, 7]]),
 array([[4, 5, 6],
        [6, 5, 4]])]

In [32]:
np.vsplit(r, 2)

[array([[1, 2, 3, 4, 5, 6]]), array([[9, 8, 7, 6, 5, 4]])]

In [3]:
#no of dimension
s = np.array([1, 2, 3, 4, 5, 6, 7])
t = np.array([[1, 2, 3, 4, 5], [5, 7, 8, 9, 0]])
u = np.array([[[1, 2, 3],[4, 5, 6]],[[8, 9, 0], [0, 1, 2]],[[4, 6, 0], [2, 4, 6]]])

print("dimension of s:", s.ndim)
print("dimension of t:", t.ndim)
print("dimension of u:", u.ndim)


dimension of s: 1
dimension of t: 2
dimension of u: 3


In [5]:
#size of array

print("size of array s", s.size)
print("size of array t", t.size)
print("size of array u", u.size)

size of array s 7
size of array t 10
size of array u 18


In [6]:
#saved file

np.save("hello.npy", u)
print("saved file")


saved file


In [7]:
pwd


'C:\\Users\\sheja'

In [9]:
v = np.load("hello.npy")
print(v)

[[[1 2 3]
  [4 5 6]]

 [[8 9 0]
  [0 1 2]]

 [[4 6 0]
  [2 4 6]]]
